#!/usr/bin/python3

# Copyright 2018, 2019 Timothy Baldwin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import itemise_git_history as igh
import sys
import argparse
import posixpath
import os

sys.setrecursionlimit(10000)
repos = dict()

parser = argparse.ArgumentParser()
parser.add_argument("--tree", default="repositories")
parser.add_argument("--remote", default="https://gitlab.riscosopen.org/")
parser.add_argument("--update", action="store_true")
parser.add_argument("products", nargs="*")
args = parser.parse_args()

if not args.products:
    args.products = igh.all_products

def get_branch(name, module, branch):
    module = posixpath.normpath(posixpath.join(product, module))
    if module.startswith("../") or module.startswith("/"):
        raise RuntimeError("Bad module name " + module)

    r = repos.get(module)
    if r is None:
        r = igh.open_repository(posixpath.join(args.remote, module), os.path.join(args.tree, module), args.update)
        r = igh.load_repository(name, r)
        repos[module] = r
    return r[branch]

for product in args.products:
    repo = igh.open_repository(posixpath.join(args.remote, product), os.path.join(args.tree, product), args.update)
    if product.endswith(".git"):
        product = product[:-4]
    out = igh.convert(repo, igh.load_repository(product, repo)["master"], posixpath.basename(product), get_branch)
    repo.create_reference("refs/heads/all-commits", out, force=True)
    del repo
